<script>
</script>

<h1>
ZARA SHOPPER
</h1>

<hr>
<h3>
    PORADNIK
</h3>
<p>
1. STWÓRZ KONTO W ZAKŁADCE UŻYTKOWNICY PODAJĄC SWOJĄ NAZWĘ ORAZ ADRES E-MAIL, NA KTÓRY MAJĄ PRZYCHODZIĆ POWIADOMIENIA.
</p>
<p>
2. WEJDŹ W SWOJE KONTO I DODAJ PRZEDMIOTY, KTÓRE CHCESZ OBSERWOWAĆ (NAZWA NIE MA ZBYTNIO ZNACZENIA, ROZMIAR MUSI BYĆ TAKI, KTÓREGO SZUKASZ), LINK MUSI PROWADZIĆ DO STRONY Z RZECZĄ
</p>
<hr>
<h3>
    TO DO:
</h3>
<p>
- OGARNIANIE WIELU ROZMIARÓW DLA JEDNEJ RZECZY<br>
- POPRAWIENIE WYGLĄDU<br>
- REFACTOR KODU<br>
- DODANIE AUTORYZACJI<br>
</p>


<style>
    * {
        color: white;
    }
</style>
